### PR TITLE
Add Chinese (zh) collation method

### PR DESCRIPTION
**Pull request by zepinglee**
1. I guess the original `languages.zj` is misspelled since `zj` isn't mapped to any language according to <https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes>. Thus I changed it to `zh`.
2. The `tailor_string()` method is modified so that it can accept the `<*` operator.
3. It looks the `[last regular]` and `'\uFDD0A'` notations are not supported (see [common/collation/zh.xml#L33-L35](https://github.com/unicode-org/cldr/blob/a6fbd0ffa1db0c9f60dc0f678ace589366ae7f3a/common/collation/zh.xml#L33-L35)). I don't quite understand them but the current implementation works.
4. Also fixed the dependencies in Makefile.

Perhaps the Chinese collection function is too long (about 60% of lines in `lua-uca-language.lua`). It is better to make it a standalone file?

### CODE REVIEW

**Comment by michal-h21** [comment]
Thanks, that looks great! I am sure there are other things that I initially didn't implement, as I was already overwhelmed by the basic functionality of the UCA algorithm. 

I've moved the Chinese library to a standalone file, as I hoped that it will make some speed difference, but it doesn't seem so. Anyway, I've also made some other changes, as I found that the names  used in `require` in `lua-uca-collator.lua` were wrong. If everything works well, I can make a new CTAN release.

**Comment by michal-h21** [comment]
Ah, yes `lua-uca.tailoring` is created when you install the package using Luarocks. I've added the command that will install the package before testing to the Makefile, so it should work now.

**Comment by zepinglee** [comment]
Yes, everything is working fine now.

**Comment by michal-h21** [comment]
OK, so I guess I can make a new release to CTAN?

**Comment by zepinglee** [comment]
> OK, so I guess I can make a new release to CTAN?

Yes. Thanks!

**Comment by michal-h21** [comment]
OK, done :)

**Pull request merged**
